# Generated by Django 2.2.5 on 2019-09-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
